parser: "@typescript-eslint/parser"

extends:
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"

parserOptions:
  ecmaVersion: 2019
  sourceType: "module"
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: "detect"

rules:
  "no-console":
    - "warn"
    - allow:
        - "error"

  "@typescript-eslint/interface-name-prefix":
    - "error"
    - "always"

  "@typescript-eslint/no-explicit-any": "off"
